### ISSUE TITLE
Pip Install failed

### ISSUE THREAD

**Issue by Revenuenexus** [Nykakin/chompjs#17]
I could not install on Windows 10 + Python 3.8

ERROR: Command errored out with exit status 1: 'c:\......\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\.....\\pip-install-3u_io6z6\\chompjs_d3345e5d833a462b9b5df7bb71a4edd2\\setup.py'"'"'; __file__='"'"'C:\\.......\\pip-install-3u_io6z6\\chompjs_d3345e5d833a462b9b5df7bb71a4edd2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\........\AppData\Local\Temp\pip-record-0jmphbm0\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\.........\appdata\local\programs\python\python38\Include\chompjs' Check the logs for full command output.

**Comment by KingTamo** [comment]
I have similar issue
Here's what I got when I tried to install on Windows 10 64 Bit and Python 3.9.1
`Collecting chompjs
  Using cached chompjs-1.0.16.tar.gz (7.0 kB)
Using legacy 'setup.py install' for chompjs, since package 'wheel' is not installed.
Installing collected packages: chompjs
    Running setup.py install for chompjs ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\future\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Future\\AppData\\Local\\Temp\\pip-install-0g3o3ido\\chompjs\\setup.py'"'"'; __file__='"'"'C:\\Users\\Future\\AppData\\Local\\Temp\\pip-install-0g3o3ido\\chompjs\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Future\AppData\Local\Temp\pip-record-u98esvgs\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\future\appdata\local\programs\python\python39\Include\chompjs'
         cwd: C:\Users\Future\AppData\Local\Temp\pip-install-0g3o3ido\chompjs\
    Complete output (19 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\chompjs
    copying chompjs\chompjs.py -> build\lib.win-amd64-3.9\chompjs
    copying chompjs\test_parser.py -> build\lib.win-amd64-3.9\chompjs
    copying chompjs\__init__.py -> build\lib.win-amd64-3.9\chompjs
    running egg_info
    writing chompjs.egg-info\PKG-INFO
    writing dependency_links to chompjs.egg-info\dependency_links.txt
    writing top-level names to chompjs.egg-info\top_level.txt
    reading manifest file 'chompjs.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'chompjs.egg-info\SOURCES.txt'
    running build_ext
    building '_chompjs' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\future\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Future\\AppData\\Local\\Temp\\pip-install-0g3o3ido\\chompjs\\setup.py'"'"'; __file__='"'"'C:\\Users\\Future\\AppData\\Local\\Temp\\pip-install-0g3o3ido\\chompjs\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Future\AppData\Local\Temp\pip-record-u98esvgs\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\future\appdata\local\programs\python\python39\Include\chompjs' Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'c:\users\future\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.`

**Comment by KingTamo** [comment]
Installing Microsoft Visual C++ Build Tools would help in solving the problem. Here's the link http://go.microsoft.com/fwlink/?LinkId=691126&fixForIE=.exe
