### ISSUE TITLE
Can't parse object

### ISSUE THREAD

**Issue by kopyl** [Nykakin/chompjs#56]
This library can't decode JSON objects which have escaped double quotes.

```
results_json = """{
    title: "\"Picnic collective\" logo and characters",
}"""

results = parse_js_object(results_json)
```

And then we'll get this error:
```
JSONDecodeError: Expecting ',' delimiter: line 1 column 12 (char 11)
```

**Comment by Nykakin** [comment]
Within triple quoted string literal `"` and `\"` are evaluated to the same:
```python
>>> """ " """
' " '
>>> """ \" """
' " '
```
Meaning that your literal is interpreting as having two consecutive quotes:
```python
>>> """{title: "\"Picnic collective\" logo and characters",}"""
'{title: ""Picnic collective" logo and characters",}'
```
Which is an invalid input.

So I think the issue here is how do you obtain your data. Is this from parsing some actual website? If so, can you provide the link and code you've used to obtain input string?

**Comment by Nykakin** [comment]
Closed due to inactivity.
