### ISSUE TITLE
Future: support for ecmascript tuples-and-records?

### ISSUE THREAD

**Issue by jayaddison** [Nykakin/chompjs#66]
Hi @Nykakin - I'm searching the web to try to figure out what options might be available to parse [ECMAScript `Tuple` and `Record`](https://github.com/tc39/proposal-record-tuple) syntax -- if/when that proposal is accepted.

Roughly speaking, it's a way to declare immutable datastructures within JavaScript code.  So where we might previously have found `const x = [1,2,3]` and retrieved a (modifiable) `Array`, instead we could find `const x = #[1,2,3]`, a `Tuple` that cannot be modified by code after the value is assigned.

In the use case I'm thinking about -- parsing the datastructures from a Sphinx `searchindex.js` file, that might in future use `Tuple` and `Record` syntax -- I don't really care about whether the resulting Python datastructures are immutable (so it doesn't matter to me whether they are `frozenlist` or `frozendict`, for example) -- but I am trying to think of ways that I can parse that  data accurately, using a proper lexer/parser that would skip `#[` fragments within string literals, and so on.

If I were to prepare a pull request -- even if it's a long-lived branch while we wait for the TC39 proposal -- would that be acceptable here?  If it's not something you'd consider supporting at all, that's OK too - I can continue on searching for other parsers.

Thanks!
James

**Comment by jayaddison** [comment]
Also, as a sort of disclaimer, after re-reading my own message: I've only recently learned about the record-and-tuple (aka R&T) proposal -- I'm not developing/promoting it myself, but I do think it's a useful idea, and have added a few comments in their repo.  Primarily I'm interested in using it in Sphinx if it becomes available, but to do that I also anticipate a need to read the resulting syntax back using Python code.

**Comment by Nykakin** [comment]
Hi @jayaddison 

If `parse_js_onject` encounters value that it doesn't recognize as string, number, nested JSON etc., it attempts to at least store this unknown thing in a string and move on. This was originally introduced to allow parsing objects contains functions, for example:
```python
>>> chompjs.parse_js_object(""""{age: function(yearBorn,thisYear) {return thisYear - yearBorn;}}""")
{'age': 'function(yearBorn,thisYear) {return thisYear - yearBorn;}'}
```
It's not perfect because this library is not a proper JavaScript parser, but for simple cases works good enough.

As a result, library can already parse values as proposed in this extension, but it stores them as strings instead of unpacking them into dictionaries and lists:
```python
>>> chompjs.parse_js_object("""const proposal = #{
...   id: 1234,
...   title: "Record & Tuple proposal",
...   contents: `...`,
...   // tuples are primitive types so you can put them in records:
...   keywords: #["ecma", "tc39", "proposal", "record", "tuple"],
... };
... """)
{'id': 1234, 'title': 'Record & Tuple proposal', 'contents': '...', 'keywords': '#["ecma", "tc39", "proposal", "record", "tuple"]'}
>>> 
>>> chompjs.parse_js_object('''{a: #{ x: 1, y: 2 }}''')
{'a': '#{ x: 1, y: 2 }'}
```
Parsing these should be simple: just remove prefixing `#` and run through `json.loads` or `parse_js_object` again.

Some time ago I considered introducing a more powerful functions that would allow handling of spread operator (see [this proposal](https://github.com/Nykakin/chompjs/issues/53#issuecomment-1712580595)). I guess if I were to introduce a proper support for tuples and records, it would go there so that original `parse_js_object` and `parse_js_objects` functions would remain unchanged and optimized for speed. I just need to finally find some time to sit down and implement this thing.

**Comment by jayaddison** [comment]
Replying slightly-out-of-order:

> Some time ago I considered introducing a more powerful functions that would allow handling of spread operator (see [this proposal](https://github.com/Nykakin/chompjs/issues/53#issuecomment-1712580595)). I guess if I were to introduce a proper support for tuples and records, it would go there so that original `parse_js_object` and `parse_js_objects` functions would remain unchanged and optimized for speed. I just need to finally find some time to sit down and implement this thing.

Is the performance concern there about handling the `.` character as an as-yet-unhandled token?  (makes sense to me if so; even a single additional comparison can make a big difference in well-optimized code).

> Parsing these should be simple: just remove prefixing `#` and run through `json.loads` or `parse_js_object` again.

Ok; initially that makes sense to me, and I feel that with some type-checks and structural checks, that may well be good enough.  It'll probably require a few passes over the data; for the Sphinx use-case the data has a fixed depth, so I expect that'd be fine.

I'll try to implement that as a prototype soon to get a sense for whether I've overlooked anything.  Thank you very much!

(please feel free to close this if you like; I can open a separate bugreport if a prototype uncovers anything else to consider)

**Comment by Nykakin** [comment]
> Is the performance concern there about handling the . character as an as-yet-unhandled token? (makes sense to me if so; even a single additional comparison can make a big difference in well-optimized code).

Exactly, and I imagine this particular extension will not appear in input data that often. Which is why it makes sense to me to have two functions: fast one for usual cases and a bit slower but more powerful.

> Ok; initially that makes sense to me, and I feel that with some type-checks and structural checks, that may well be good enough. It'll probably require a few passes over the data; for the Sphinx use-case the data has a fixed depth, so I expect that'd be fine.

You can customize parser and make it call `parse_js_object` recursively upon encountering string starting with `#`. Should work for nested tuples:
```python
from json import scanner, JSONDecoder
from json.decoder import scanstring

import chompjs


def custom_scanstring(*args, **kwargs):
    (s, end) = scanstring(*args, **kwargs)
    if s.startswith("#"):
        return chompjs.parse_js_object(s, loader_kwargs={'cls': CustomJsonDecoder}), end
    else:
        return (s, end)


class CustomJsonDecoder(JSONDecoder):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.parse_string = custom_scanstring
        self.scan_once = scanner.py_make_scanner(self)
        

result = chompjs.parse_js_object(
    "{'test': #[1, 2, 3, #[4, 5, 6, #[7, 8, 9]]]}",
    loader_kwargs={'cls': CustomJsonDecoder}
)
assert result == {'test': [1, 2, 3, [4, 5, 6, [7, 8, 9]]]}
```

**Comment by jayaddison** [comment]
Thanks again for your replies @Nykakin - I think this can be closed; I'm reassured that the parser here should be usable (with some marginal additional work) if+when tuples-and-records lands.
